"""Build the durable cardio log — non-run aerobic work (elliptical, bike, etc).

Cross-training is a real part of the plan: it's how aerobic base gets built when
the Achilles/legs need sparing (and it'll matter through the August ramp). But
build_run_log.py only tracks sport='Run', so these sessions lived ONLY in the
gitignored SQLite DB — invisible to reviews and lost on any rebuild. This fixes
that with the same treatment runs get: HR-zone distribution + cardiac drift.

Deliberately EXCLUDED, to avoid double-counting or noise:
  - Run            -> run_log.jsonl
  - Rowing/VirtualRow -> rowing_log.jsonl (authoritative, from Concept2 exports)
  - WeightTraining -> strength_log.jsonl
  - Walk           -> incidental daily movement, not training (tracked via steps)
  - Yoga/Pilates   -> mobility, not aerobic training

Zones come from fitness.zones (shared with build_run_log.py — one source of truth).
Idempotent: rebuilds wholesale from the DB every run.

Run: .venv/bin/python scripts/build_cardio_log.py
"""
import csv
import io
import json
import sqlite3
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DB = ROOT / "data" / "fitness.db"
sys.path.insert(0, str(ROOT / "src"))
from fitness.zones import zone_dist, drift_quarters  # noqa: E402

CARDIO_SPORTS = ("Workout", "Ride", "VirtualRide", "Swim", "StairStepper", "Elliptical")
MIN_MINUTES = 10   # below this it's not an aerobic session worth trending


def load_existing():
    """Existing log keyed by activity_id — so hand-entered `manual` readings
    (machine-console watts etc, which exist in NO API) survive a rebuild."""
    p = ROOT / "data" / "cardio_log.jsonl"
    if not p.exists():
        return {}
    return {r["activity_id"]: r for r in
            (json.loads(l) for l in p.read_text().splitlines() if l.strip())}


def main():
    existing = load_existing()
    con = sqlite3.connect(DB)
    stream_ids = {r[0] for r in con.execute("SELECT DISTINCT activity_id FROM activity_streams")}
    ph = ",".join("?" * len(CARDIO_SPORTS))
    rows = con.execute(
        f"SELECT id, start_time, name, sport, distance_m, moving_time_s, avg_hr, max_hr "
        f"FROM activities WHERE sport IN ({ph}) ORDER BY start_time", CARDIO_SPORTS
    ).fetchall()

    records = []
    for aid, start, name, sport, dist_m, mov_s, avg_hr, max_hr in rows:
        if not mov_s or mov_s < MIN_MINUTES * 60:
            continue
        rec = {
            "activity_id": aid,
            "date": start[:10],
            "start_time": start,
            "name": name,
            "sport": sport,
            "duration_min": round(mov_s / 60, 1),
            "distance_km": round(dist_m / 1000, 2) if dist_m else None,
            "avg_hr": round(avg_hr, 1) if avg_hr is not None else None,
            "max_hr": int(max_hr) if max_hr is not None else None,
            "zones_pct": None, "z1_z2_pct": None, "z4_z5_pct": None,
            "drift_quarters": None,
        }
        if aid in stream_ids:
            s = json.loads(con.execute(
                "SELECT streams_json FROM activity_streams WHERE activity_id=?", (aid,)).fetchone()[0])
            hr, t = s.get("heartrate"), s.get("time")
            tz = zone_dist(hr, t)
            if tz:
                tot = sum(tz.values())
                rec["zones_pct"] = {z: round(100 * tz[z] / tot, 1) for z in tz}
                rec["z1_z2_pct"] = round(100 * (tz["Z1"] + tz["Z2"]) / tot, 1)
                rec["z4_z5_pct"] = round(100 * (tz["Z4"] + tz["Z5"]) / tot, 1)
            rec["drift_quarters"] = drift_quarters(hr)
        # Preserve any hand-entered machine-console readings across the rebuild.
        prev = existing.get(aid) or {}
        rec["manual"] = prev.get("manual")
        records.append(rec)

    with open(ROOT / "data" / "cardio_log.jsonl", "w") as f:
        for r in records:
            f.write(json.dumps(r) + "\n")

    out = io.StringIO()
    w = csv.writer(out)
    w.writerow(["CARDIO LOG — non-run aerobic work (elliptical/bike/swim), auto-generated by "
                "build_cardio_log.py. Runs are in the Run Log; rowing in rowing_log.jsonl."])
    w.writerow([])
    w.writerow(["Date", "Sport", "Name", "Duration (min)", "Distance (km)", "Avg HR", "Max HR",
                "Z1%", "Z2%", "Z3%", "Z4%", "Z5%", "Z1+Z2%", "Z4+Z5%", "Drift Q1->Q4",
                "Avg Power (W, machine)"])
    for r in records:
        zp = r["zones_pct"] or {}
        dq = r["drift_quarters"]
        w.writerow([r["date"], r["sport"], r["name"], r["duration_min"], r["distance_km"] or "",
                    r["avg_hr"] if r["avg_hr"] is not None else "",
                    r["max_hr"] if r["max_hr"] is not None else "",
                    zp.get("Z1", ""), zp.get("Z2", ""), zp.get("Z3", ""), zp.get("Z4", ""), zp.get("Z5", ""),
                    r["z1_z2_pct"] if r["z1_z2_pct"] is not None else "",
                    r["z4_z5_pct"] if r["z4_z5_pct"] is not None else "",
                    " -> ".join(str(x) for x in dq) if dq else "",
                    (r.get("manual") or {}).get("avg_power_w", "")])
    (ROOT / "data" / "cardio_log.csv").write_text(out.getvalue())

    with_z = sum(1 for r in records if r["zones_pct"])
    print("Wrote data/cardio_log.jsonl + data/cardio_log.csv")
    print(f"  Cardio sessions: {len(records)} (>= {MIN_MINUTES} min)")
    print(f"  With HR-zone distribution: {with_z}")
    from collections import Counter
    for sp, n in Counter(r["sport"] for r in records).most_common():
        print(f"    {sp:14} {n}")


if __name__ == "__main__":
    main()
